
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYDaQcX1eKnBHG8Al2KhI3p0McISIWkT4',
    authDomain: 'dronethebeat.firebaseapp.com',
    projectId: 'dronethebeat',
    storageBucket: 'dronethebeat.appspot.com',
    messagingSenderId: '110358591512',
    appId: '1:110358591512:web:1908c27963a5de99fdab6d'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD3p9lSEEfJUmMGDiiopEx7dx4IHxQPyU',
    appId: '1:110358591512:android:8b7f749200209b4ffdab6d',
    messagingSenderId: '110358591512',
    projectId: 'dronethebeat',
    storageBucket: 'dronethebeat.appspot.com'
  );
}
